### PR TITLE
[fix] Remove without_storage_info from runtime

### LINKED ISSUE #286: Depreciation warnings
**Issue summary**

There are a lot of deprecation warnings in the code which make the output extremely noisy. They should probably be fixed.

```
warning: use of deprecated struct `pallet::warnings::swap`:
Implicit call indices are deprecated in favour of explicit ones.
Please ensure that all calls have the `pallet::call_index` attribute or that the
`dev-mode` of the pallet is enabled. For more info see:
<https://github.com/paritytech/substrate/pull/12891> and
<https://github.com/paritytech/substrate/pull/11381>.
--> pallets/anonymity-mining/src/lib.rs:168:10
|
168 |         pub fn swap(
|                ^^^^
|
= note: `#[warn(deprecated)]` on by default
```
**Other information and links**

I think this was introduced by https://github.com/webb-tools/protocol-substrate/pull/282

### PR DESCRIPTION
**Pull request by 1xstj**
**Summary of changes**
Changes introduced in this pull request:
- remove without_storage_info from runtime
- replace all Vec<> with BoundedVec<> in runtime
- Add call indices for all pallets

**Reference issue to close (if applicable)**
Part of SBP Review #283
Also closes #286

### CODE REVIEW

**Comment by drewstone** [comment]
Addresses #283

File: pallets/asset-registry/src/tests.rs [hunk 1]
```diff
@@ -21,35 +21,35 @@ use crate::{
...
-		assert_noop!(
-			AssetRegistryPallet::register(
-				RuntimeOrigin::root(),
-				too_long.to_vec(),
-				AssetType::Token,
-				ed
-			),
-			Error::<Test>::TooLong
-		);
+		// assert_noop!(
```
Comment (drewstone) [inline pallets/asset-registry/src/tests.rs:38]: @1xstj can we remove these if they're meant to be commented out in a new PR.
